"""HLAL (Wahed FTSE USA Shariah ETF) tarkibiy qismlari — taktik watchlist seed'i.

BU FAYL AVTOMATIK GENERATSIYA QILINGAN. Manba: data/hlal_holdings.csv
(HLAL ETF rasmiy holdings eksporti). Qayta generatsiya: scripts/build_tactical_watchlist.py

Faqat OMMAVIY ma'lumot: ticker + kompaniya nomi. Halal/harom QAROR shu yerda
HISOBLANMAYDI — ro'yxat manbasi HLAL (o'zi sharia ETF) holdings, xuddi mavjud
CORE_WATCHLIST seed'idagi ETF-holdings konvensiyasi kabi. last_reviewed=None
qoladi (bu asbob orqali qayta tekshirilmagan — soxta sana qo'yilmaydi).

Shaxsiy jurnal / runtime o'zgarishlar core_watchlist.json'da (gitignore) qoladi;
bu seed esa deploy bilan ketadi, shunda Railway'da ham /scan va /watchlist to'liq
ro'yxatni ko'radi (JSON fayli bo'lmasa).
"""

from __future__ import annotations

# (ticker, kompaniya nomi) — data/hlal_holdings.csv dan. Tartib: CSV tartibi.
HLAL_HOLDINGS: list[tuple[str, str]] = [
    ("TPG", "TPG Inc"),
    ("A", "Agilent Technologies Inc"),
    ("AAPL", "Apple Inc"),
    ("ABT", "Abbott Laboratories"),
    ("ADBE", "Adobe Inc"),
    ("ADI", "Analog Devices Inc"),
    ("ADM", "Archer-Daniels-Midland Co"),
    ("ADSK", "Autodesk Inc"),
    ("AMAT", "Applied Materials Inc"),
    ("AMD", "Advanced Micro Devices Inc"),
    ("APTV", "Aptiv PLC"),
    ("ATO", "Atmos Energy Corp"),
    ("AVGO", "Broadcom Inc"),
    ("AXON", "Axon Enterprise Inc"),
    ("BIIB", "Biogen Inc"),
    ("BKR", "Baker Hughes Co"),
    ("BSX", "Boston Scientific Corp"),
    ("BURL", "Burlington Stores Inc"),
    ("CAH", "Cardinal Health Inc"),
    ("CARR", "Carrier Global Corp"),
    ("CBRE", "CBRE Group Inc"),
    ("CDNS", "Cadence Design Systems Inc"),
    ("CDW", "CDW Corp/DE"),
    ("CHD", "Church & Dwight Co Inc"),
    ("CIEN", "Ciena Corp"),
    ("CMI", "Cummins Inc"),
    ("COHR", "Coherent Corp"),
    ("COO", "Cooper Cos Inc/The"),
    ("COP", "ConocoPhillips"),
    ("COR", "Cencora Inc"),
    ("CRH", "CRH PLC"),
    ("CRM", "Salesforce Inc"),
    ("CSCO", "Cisco Systems Inc"),
    ("CSGP", "CoStar Group Inc"),
    ("CTAS", "Cintas Corp"),
    ("CTVA", "Corteva Inc"),
    ("CVNA", "Carvana Co"),
    ("CVX", "Chevron Corp"),
    ("DAL", "Delta Air Lines Inc"),
    ("DD", "DUPONT DE NEMOURS INC"),
    ("DELL", "Dell Technologies Inc"),
    ("DGX", "Quest Diagnostics Inc"),
    ("DHI", "DR Horton Inc"),
    ("DHR", "Danaher Corp"),
    ("DLR", "Digital Realty Trust Inc"),
    ("DLTR", "Dollar Tree Inc"),
    ("DOCU", "Docusign Inc"),
    ("DOV", "Dover Corp"),
    ("DOW", "Dow Inc"),
    ("DVN", "Devon Energy Corp"),
    ("EBAY", "eBay Inc"),
    ("ECL", "Ecolab Inc"),
    ("EL", "Estee Lauder Cos Inc/The"),
    ("EMR", "Emerson Electric Co"),
    ("EOG", "EOG Resources Inc"),
    ("EW", "Edwards Lifesciences Corp"),
    ("EXE", "Expand Energy Corp"),
    ("EXPD", "Expeditors International of Washington Inc"),
    ("FAST", "Fastenal Co"),
    ("FDX", "FedEx Corp"),
    ("FDXF", "Fedex Freight Holding Co Inc"),
    ("FERG", "Ferguson Enterprises Inc"),
    ("FFIV", "F5 Inc"),
    ("FIX", "Comfort Systems USA Inc"),
    ("FLEX", "Flex Ltd"),
    ("FSLR", "First Solar Inc"),
    ("FTV", "Fortive Corp"),
    ("FWONA", "Liberty Media Corp-Liberty Formula One"),
    ("FWONK", "Liberty Media Corp-Liberty Formula One"),
    ("GDDY", "GoDaddy Inc"),
    ("GEHC", "GE HealthCare Technologies Inc"),
    ("GEV", "GE Vernova Inc"),
    ("GFS", "GLOBALFOUNDRIES Inc"),
    ("GILD", "Gilead Sciences Inc"),
    ("GLW", "Corning Inc"),
    ("GOOG", "Alphabet Inc"),
    ("GOOGL", "Alphabet Inc"),
    ("GPC", "Genuine Parts Co"),
    ("GRMN", "Garmin Ltd"),
    ("GWW", "WW Grainger Inc"),
    ("HAL", "Halliburton Co"),
    ("HPE", "Hewlett Packard Enterprise Co"),
    ("HPQ", "HP Inc"),
    ("HSY", "Hershey Co/The"),
    ("HUBB", "Hubbell Inc"),
    ("IDXX", "IDEXX Laboratories Inc"),
    ("IEX", "IDEX Corp"),
    ("IFF", "International Flavors & Fragrances Inc"),
    ("ILMN", "Illumina Inc"),
    ("INTC", "Intel Corp"),
    ("IP", "International Paper Co"),
    ("IR", "Ingersoll Rand Inc"),
    ("ISRG", "Intuitive Surgical Inc"),
    ("IT", "Gartner Inc"),
    ("J", "Jacobs Solutions Inc"),
    ("JBHT", "JB Hunt Transport Services Inc"),
    ("JCI", "Johnson Controls International plc"),
    ("JNJ", "Johnson & Johnson"),
    ("KDP", "Keurig Dr Pepper Inc"),
    ("KLAC", "KLA CORP"),
    ("KO", "Coca-Cola Co/The"),
    ("KVUE", "Kenvue Inc"),
    ("LEN", "Lennar Corp"),
    ("LEN-B", "Lennar Corp"),
    ("LH", "Labcorp Holdings Inc"),
    ("LIN", "Linde PLC"),
    ("LLY", "Eli Lilly & Co"),
    ("LRCX", "Lam Research Corp"),
    ("LULU", "Lululemon Athletica Inc"),
    ("LUV", "Southwest Airlines Co"),
    ("LYB", "LyondellBasell Industries NV"),
    ("MCK", "McKesson Corp"),
    ("MDLN", "Medline Inc"),
    ("MDLZ", "Mondelez International Inc"),
    ("MDT", "Medtronic PLC"),
    ("META", "Meta Platforms Inc"),
    ("MKC", "McCormick & Co Inc/MD"),
    ("MLM", "Martin Marietta Materials Inc"),
    ("MMM", "3M Co"),
    ("MNST", "Monster Beverage Corp"),
    ("MPWR", "Monolithic Power Systems Inc"),
    ("MRK", "Merck & Co Inc"),
    ("MRVL", "MARVELL TECHNOLOGY INC"),
    ("MSFT", "Microsoft Corp"),
    ("MSTR", "Strategy Inc"),
    ("MU", "Micron Technology Inc"),
    ("NEM", "Newmont Corp"),
    ("NKE", "NIKE Inc"),
    ("NOW", "ServiceNow Inc"),
    ("NTAP", "NetApp Inc"),
    ("NUE", "Nucor Corp"),
    ("NVDA", "NVIDIA Corp"),
    ("NVR", "NVR Inc"),
    ("NWS", "News Corp"),
    ("NWSA", "News Corp"),
    ("NXPI", "NXP Semiconductors NV"),
    ("ODFL", "Old Dominion Freight Line Inc"),
    ("OKTA", "Okta Inc"),
    ("OMC", "Omnicom Group Inc"),
    ("ON", "ON Semiconductor Corp"),
    ("OXY", "Occidental Petroleum Corp"),
    ("PANW", "Palo Alto Networks Inc"),
    ("PFE", "Pfizer Inc"),
    ("PG", "Procter & Gamble Co/The"),
    ("PHM", "PulteGroup Inc"),
    ("PINS", "Pinterest Inc"),
    ("PKG", "Packaging Corp of America"),
    ("PNR", "Pentair PLC"),
    ("PODD", "Insulet Corp"),
    ("PPG", "PPG Industries Inc"),
    ("PSX", "Phillips 66"),
    ("PTC", "PTC Inc"),
    ("PWR", "Quanta Services Inc"),
    ("Q", "Qnity Electronics Inc"),
    ("QCOM", "QUALCOMM Inc"),
    ("RBLX", "ROBLOX Corp"),
    ("REGN", "Regeneron Pharmaceuticals Inc"),
    ("RMD", "ResMed Inc"),
    ("ROK", "Rockwell Automation Inc"),
    ("ROL", "Rollins Inc"),
    ("ROP", "Roper Technologies Inc"),
    ("ROST", "Ross Stores Inc"),
    ("SCCO", "Southern Copper Corp"),
    ("SLB", "SLB Ltd"),
    ("SMCI", "Super Micro Computer Inc"),
    ("SNA", "Snap-on Inc"),
    ("SNDK", "Sandisk Corp"),
    ("SNPS", "Synopsys Inc"),
    ("SRE", "Sempra"),
    ("STE", "STERIS PLC"),
    ("STLD", "Steel Dynamics Inc"),
    ("STX", "Seagate Technology Holdings PLC"),
    ("SUI", "Sun Communities Inc"),
    ("SW", "Smurfit Westrock PLC"),
    ("SYK", "Stryker Corp"),
    ("T", "AT&T Inc"),
    ("TEAM", "Atlassian Corp"),
    ("TEL", "TE Connectivity PLC"),
    ("TER", "Teradyne Inc"),
    ("TJX", "TJX Cos Inc/The"),
    ("TPL", "Texas Pacific Land Corp"),
    ("TRMB", "Trimble Inc"),
    ("TSCO", "Tractor Supply Co"),
    ("TSLA", "Tesla Inc"),
    ("TT", "Trane Technologies PLC"),
    ("TTWO", "Take-Two Interactive Software Inc"),
    ("TWLO", "Twilio Inc"),
    ("TXN", "Texas Instruments Inc"),
    ("TYL", "Tyler Technologies Inc"),
    ("UAL", "United Airlines Holdings Inc"),
    ("UBER", "Uber Technologies Inc"),
    ("UI", "Ubiquiti Inc"),
    ("ULTA", "ULTA BEAUTY INC"),
    ("UPS", "United Parcel Service Inc"),
    ("VGNT", "Versigent PLC"),
    ("VLO", "Valero Energy Corp"),
    ("VLTO", "Veralto Corp"),
    ("VMC", "Vulcan Materials Co"),
    ("VRT", "Vertiv Holdings Co"),
    ("VRTX", "Vertex Pharmaceuticals Inc"),
    ("WAB", "Westinghouse Air Brake Technologies Corp"),
    ("WAT", "Waters Corp"),
    ("WDAY", "Workday Inc"),
    ("WDC", "Western Digital Corp"),
    ("WELL", "Welltower Inc"),
    ("WSM", "Williams-Sonoma Inc"),
    ("WST", "West Pharmaceutical Services Inc"),
    ("WY", "Weyerhaeuser Co"),
    ("XOM", "ExxonMobil Holdings Corp"),
    ("XYL", "Xylem Inc/NY"),
    ("ZBH", "ZIMMER BIOMET HOLDINGS INC"),
]
